### ISSUE TITLE
编译报错了

### ISSUE THREAD

**Issue by zfenggo** [diylxy/LiThermal#1]
编译报错了，不知道是不是我没配置好。已经更换成自己的编译器路径。
![image](https://github.com/user-attachments/assets/eb0bbb76-4f51-495e-931a-324c3596b3e3)

**Comment by diylxy** [comment]
你需要按照
https://github.com/diylxy/LiThermal_Compiler
中的方法编译

**Comment by diylxy** [comment]
closed for inactivity
