### ISSUE TITLE
中心值标签与最大值/最小值标签重合问题

### ISSUE THREAD

**Issue by hyj727** [diylxy/LiThermal#11]
如果打开中心值，再开最大值或最小值，中心值标签会和最大值/最小值重合
![微信图片_20241213220305](https://github.com/user-attachments/assets/10552b3c-3869-4360-9f98-a3ce0c53da3a)

**Comment by hyj727** [comment]
![Uploading 微信图片_20241213220305.jpg…]()

**Comment by diylxy** [comment]
海康后台“测温”里有个选项，配置最值显示位置的，具体名字记不清了

**Comment by hyj727** [comment]
好的up，已通过调整海康后台解决，感谢解答
