### ISSUE TITLE
单片机烧录power.hex后长按按键，en1没有高电平产生

### ISSUE THREAD

**Issue by pine-fish** [diylxy/LiThermal#3]
单片机烧录一次hex后，需要按住按键上电才能再次进入下载模式，说明单片机和按键是没问题的，但是上电后长按按键，en1不产生高电平导致无法产生0.9、1.5和3.3三个电压（手动短接en1和vcc_pmu是能正常产生三个电压的），这个可能是什么问题呢？

**Comment by diylxy** [comment]
单片机焊接问题

**Comment by pine-fish** [comment]
但是我重新焊接过一次，测了焊点，也是通的呀 vcc_pmu正常是4.8v左右没错吧？

**Comment by diylxy** [comment]
嗯，所以如果单片机本身没坏，那就只能是焊接问题

**Comment by pine-fish** [comment]
ok 我晚上把单片机拆下来单独接漆包线试试

**Comment by pine-fish** [comment]
找到问题了 焊接没问题 是en1连着的那个ao3402坏了 en1一直被拉低 拆掉3402就一切正常 感谢帮助！
