### ISSUE TITLE
准星不在画面中心

### ISSUE THREAD

**Issue by XUANHLGG** [diylxy/LiThermal#4]
![127 0 0 1_01_2024102611380612](https://github.com/user-attachments/assets/40f7d63b-c287-4dd6-a64c-8792c3939678)
如图，准星在画面偏下位置，在 README 中有相关说明，但在海康后台未找到相关设置，感谢

> 中心值不在中心，或者希望自定义中心值显示
如果已经焊接，可以[配置端口转发](https://github.com/diylxy/LiThermal_Tools/blob/master/%E9%85%8D%E7%BD%AE%E7%AB%AF%E5%8F%A3%E8%BD%AC%E5%8F%91.md)后进入海康后台修改。

![image](https://github.com/user-attachments/assets/16b709af-475f-4aff-a581-5022aecd64ae)
![image](https://github.com/user-attachments/assets/a3420006-d33b-42f6-972b-5f01c35381cf)

**Comment by diylxy** [comment]
在黑体校正那里选点

**Comment by XUANHLGG** [comment]
> 在黑体校正那里选点

感谢
