### ISSUE TITLE
希望加入录像保留UI功能

### ISSUE THREAD

**Issue by XUANHLGG** [diylxy/LiThermal#8]
如题，拍照可以保留UI（可拍下最大值、最小值等），但录像只能开中心值，中心值只能测出准星位置的温度且又与实际温度相差甚远，所以希望能加入此功能，感谢！

**Comment by diylxy** [comment]
[c7d3261](https://github.com/diylxy/LiThermal/commit/c7d3261c6ecbf793bab42eb339f3cd7a2d8332c6)已实现，可以在[LiThermal_Compiler](https://github.com/diylxy/LiThermal_Compiler)按说明下载最新固件。如需录像保留UI可在系统设置中打开`内置准星`选项（个人感觉不太好看）。

**Comment by XUANHLGG** [comment]
> [c7d3261](https://github.com/diylxy/LiThermal/commit/c7d3261c6ecbf793bab42eb339f3cd7a2d8332c6)已实现，可以在[LiThermal_Compiler](https://github.com/diylxy/LiThermal_Compiler)按说明下载最新固件。如需录像保留UI可在系统设置中打开`内置准星`选项（个人感觉不太好看）。

感谢！

**Comment by XUANHLGG** [comment]
> [c7d3261](https://github.com/diylxy/LiThermal/commit/c7d3261c6ecbf793bab42eb339f3cd7a2d8332c6)已实现，可以在[LiThermal_Compiler](https://github.com/diylxy/LiThermal_Compiler)按说明下载最新固件。如需录像保留UI可在系统设置中打开`内置准星`选项（个人感觉不太好看）。

感谢！想请问下有没有办法实现录像时录下拍照时较为好看的温度显示UI呢？

**Comment by diylxy** [comment]
直接转储framebuffer，但考虑到性能问题我不准备做
